<a href="https://colab.research.google.com/github/JAPV180370/mineria_datos/blob/main/mineria_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Minería de Datos**

## Parcial 1

#### **Introducción**

La minería de datos se establece como una disciplina interdisciplinaria que combina estadística, inteligencia artificial y sistemas de bases de datos para extraer información implícita y procesable. Su propósito es la transición del almacenamiento masivo de datos hacia la generación de valor estratégico mediante el descubrimiento de estructuras no triviales.

---

#### **Conceptos**

**Proceso KDD**

Metodología sistemática que engloba la selección, limpieza y transformación de datos, seguida de la aplicación de algoritmos y la interpretación de los resultados para obtener conocimiento válido.


**Modelado Supervisado**

Enfoque orientado a la clasificación y regresión, donde el algoritmo aprende de datos históricos etiquetados para predecir etiquetas o valores numéricos en nuevas instancias.


**Modelado No Supervisado**

Técnica enfocada en el descubrimiento de patrones intrínsecos o agrupamientos (clustering) en datos que carecen de etiquetas previas, facilitando la identificación de estructuras ocultas.

**Reglas de Asociación**

Análisis de dependencias que identifica la probabilidad de ocurrencia conjunta de eventos, permitiendo descubrir relaciones de causalidad o correlación en grandes conjuntos transaccionales.

---

#### **Ciencia de Datos**

La Ciencia de Datos constituye el marco holístico que integra la minería de datos junto con técnicas de visualización, ingeniería de datos y computación científica. Mientras que la minería se enfoca específicamente en la extracción de patrones, la Ciencia de Datos abarca todo el ciclo de vida de la información, desde la arquitectura de ingesta hasta la comunicación de hallazgos para la toma de decisiones complejas y la automatización mediante modelos de aprendizaje automático (Machine Learning).

---

Help and Documentation in IPython

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

In [ ]:
L.<TAB>

SyntaxError: invalid syntax (ipython-input-3018186219.py, line 1)

In [ ]:
L.cou<TAB>

AttributeError: 'list' object has no attribute 'cou'

In [ ]:
from itertools import co<TAB>

SyntaxError: invalid syntax (ipython-input-461150734.py, line 1)

In [ ]:
import <TAB>

SyntaxError: invalid syntax (ipython-input-709411292.py, line 1)

In [ ]:
*Warning?

In [ ]:
str.*find*?

---

IPython Magic Commands

In [ ]:
# El comando mágico %timeit sirve para evaluar el desempeño, en términos de tiempo.
%timeit L = [n ** 2 for n in range(1000)]

67.5 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando mágico %%timeit sirve tambien para evaluar el desempeño, sólo que este abarca varias líneas de código en lugar de una.
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

106 µs ± 43.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

---

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'fea53c29de17',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

---

Understanding Data Types in Python

In [ ]:
import numpy as np

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

---

The Basics of NumPy Arrays

In [1]:
import numpy as np

In [3]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim) # La propiedad ndim nos dice el número de dimensiones.
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print("dtype:", x3.dtype)

dtype: int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


---

Array Indexing: Accessing Single Elements

In [12]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[0] # Se coloca el índice del elemento que ser quiera obtener, que en este caso es el '5'.

np.int64(5)

In [11]:
x1[4]

np.int64(7)

In [13]:
x1[-1]

np.int64(9)

In [14]:
x1[-2]

np.int64(7)

In [15]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x2[0, 0]

np.int64(3)

In [17]:
x2[2, 0]

np.int64(1)

In [21]:
x2[2, -1]

np.int64(7)

In [22]:
x2[0, 0] = 12 # Se cambia el valor de la celda indicada a '12'.
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [23]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

---

#### **Estadística básica**

Media (Mean)

In [24]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


---

Promedio (Average) y Promedio Ponderado

In [33]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


---

Mediana

In [30]:
mediana = np.median(data)
print(mediana)

3.0


---

Varianza y Desviación Estándar

In [32]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


---

Generación de Datos Aleatorios

In [34]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


---

Correlación

In [36]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])